# Generated by Django 4.1.5 on 2023-02-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatroom_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.chatroom'),
            preserve_default=False,
        ),
    ]
